/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.CodeMain.view.Form_chucNang.FRM_HoTro;

import com.CodeMain.domainModel.HoaDon;
import com.CodeMain.domainModel.KhachHang;
import com.CodeMain.services.HoaDonCTService;
import com.CodeMain.services.HoaDonService;
import com.CodeMain.services.KhachHangService;
import com.CodeMain.services.serviceImp.HoaDonCTServiceImp;
import com.CodeMain.services.serviceImp.HoaDonServiceImp;
import com.CodeMain.services.serviceImp.KhachHangServiceImp;
import com.CodeMain.view.Form_chucNang.FrmBanHang;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hungs
 */
public class TTKH extends javax.swing.JFrame {

    KhachHangService KHService;
    DefaultTableModel dtm;
    HoaDonService hoaDonService;
    FrmBanHang frmBH;

    public TTKH() {
        initComponents();
        this.setLocationRelativeTo(null);
        KHService = new KhachHangServiceImp();
        dtm = (DefaultTableModel) tblBangKH.getModel();
        frmBH = new FrmBanHang();
        hoaDonService = new HoaDonServiceImp();
        loadTable();
    }

    void loadTable() {
        dtm.setRowCount(0);
        KHService.getListAll().forEach(x -> {
            dtm.addRow(new Object[]{
                x.getMa(), x.getHoTen(), x.isGioiTinh() == true ? "Nam" : "Nữ", x.getNgaySinh(), x.getEmail(), x.getSdt(),
                x.getDiaChi(), x.isDeleted() == false ? "Đã nghỉ" : "Đang làm"
            });
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblBangKH = new javax.swing.JTable();
        btnChon = new javax.swing.JButton();
        lblTenkh = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblBangKH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã KH", "Họ tên", "Giới tính", "Ngày sinh", "email", "sdt", "địa chỉ", "Trạng thái"
            }
        ));
        tblBangKH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBangKHMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBangKH);

        btnChon.setText("Chọn");
        btnChon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addComponent(btnChon, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblTenkh, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(lblTenkh, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(btnChon)
                .addContainerGap(118, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void btnChonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonActionPerformed
        HoaDon hd = FrmBanHang.hoaDonCho;
        if (hd != null) {
            hd.setKhachHang(KHChon);
            frmBH.updateHoaDon(hd);
            this.dispose();
        }
        rowCLbang = -1;

    }//GEN-LAST:event_btnChonActionPerformed
    public static KhachHang KHChon = null;

    int rowCLbang = -1;
    private void tblBangKHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBangKHMouseClicked
        // TODO add your handling code here:
        rowCLbang = tblBangKH.getSelectedRow();
        String ma = tblBangKH.getModel().getValueAt(rowCLbang, 0).toString();
        KHChon = KHService.getOneObj(ma);
        lblTenkh.setText(KHChon.getHoTen());
    }//GEN-LAST:event_tblBangKHMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TTKH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TTKH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TTKH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TTKH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TTKH().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChon;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTenkh;
    private javax.swing.JTable tblBangKH;
    // End of variables declaration//GEN-END:variables
}
